### PR TITLE
Dockerize project

### PR DESCRIPTION
**Pull request by d2bit**
That's my environment set up with docker.

### CODE REVIEW

**Comment by rewritten** [comment]
Is it working on linux or on OS X too?

**Comment by rewritten** [comment]
That's really cool. Is it like several machines which are available to each other through the 'link' stanza on the compose file? (I'm new to docker...)

Can it be automated and integrated with the ansible scripts for local development?

**Comment by enricostano** [comment]
Nice, remember that we just need a box (docker, LXC, VM, bare metal, PC, VPS, etc) that can be the target of our provisioning process. And that we want to re-use provisioning scripts (Ansbile, etc) between production and development as much as possible.

**Comment by d2bit** [comment]
yeah, it should work over OSX, as docker can run. (with some kind of vbox or so)
I really hate osx :trollface:

**Comment by enricostano** [comment]
For Linux I can offer the LXC setup that we use for Katuma. You don't even need docker.

**Comment by d2bit** [comment]
@enricostano I thought the other PR was about it. I've seen docker containers could be provisioned through ansible, but I didn't touch any ansible (not yet) But seems a really interesting idea

**Comment by enricostano** [comment]
Basic concept shown here in my last Ansible talk https://github.com/enricostano/ansible-lxc-demo

**Comment by d2bit** [comment]
:clap: :clap: I'll take a look later

**Comment by rewritten** [comment]
Ok so with this docker-compose.yml file I can set up all the images, let's see if they run unde xhyve.

**Comment by rewritten** [comment]
Status of this?

**Comment by d2bit** [comment]
In my opinion this could be closed as docker-compose won't be used..

**Comment by rewritten** [comment]
Ok thanks for the effort anyway @d2bit

**Pull request closed without merging**
