### PR TITLE
Add post ID to offers/inquiries reports

### PR DESCRIPTION
**Pull request by markets**
Supersedes and closes #571. Added ID also in CSV and PDF exports, for consistency.

Co-authored-by: @dataf3l

**EXTRA**
- refactor navbar partials: too much nested partials hurt view rendering perform
- ✂️  removed a couple of unused RJS views

### CODE REVIEW

**Comment by sseerrggii** [comment]
Thanks @markets ! 

Is it ready to test?

**Comment by markets** [comment]
Yes @sseerrggii

**Comment by sseerrggii** [comment]
:green_apple:

**Comment by sseerrggii** [comment]
:heavy_check_mark:

**Pull request merged**
