### PR TITLE
Feature/add phones search feature (only for managers)

### LINKED ISSUE #511: Members manage, add phones to searchable fields
Some community managers ask for the ability of search users by phone in the /members/manage

### PR DESCRIPTION
**Pull request by sseerrggii**
fix #511

### CODE REVIEW

**Comment by markets** [comment]
cool @sseerrggii 👍 I think this deserves a test case ensuring that search by phone is actually working, but +1 from my side!

**Comment by markets** [comment]
@sseerrggii @enricostano I just added that test case and rebased with current develop! This is now ready to review, test and merge!

**Comment by sseerrggii** [comment]
I have the same problem https://github.com/coopdevs/timeoverflow/pull/514#issuecomment-564093771

**Comment by markets** [comment]
sorry @sseerrggii 🙏 I can't help with that, but maybe after all the changes we made in the infra in the past month solved it?

**Comment by sseerrggii** [comment]
Yes @markets I will test it again

**Comment by markets** [comment]
@sseerrggii just updated with current develop (with 💚 CI)

**Comment by sseerrggii** [comment]
Tested :heavy_check_mark: 
Thank you @markets

**Comment by markets** [comment]
:+1: @sseerrggii 
Maybe we can merge this one too @sauloperez? Thanks

**Pull request merged**
