### PR TITLE
Feature/group offers

### PR DESCRIPTION
**Pull request by Morantron**
description under construction

### CODE REVIEW

**Comment by Morantron** [comment]
https://github.com/coopdevs/timeoverflow/issues/470

**Comment by Morantron** [comment]
some screenshots :camera_flash: 

tag-list

tag-detail

image

**Comment by sseerrggii** [comment]
Nice!! In form copy better as a question: "Is it a group offer?" 

Other problem is that we will use this for offeres and for inquiries (demands) so... copies will be: 

"Group Offer"
"Group Inquirie"
"Is it a group offer?"
"Is it a group inquire?"

I will translate this to other languages after merge

**Comment by Morantron** [comment]
perfeito

**Comment by enricostano** [comment]
@Morantron cool! :muscle: 

Would you mind to update [view tests](https://github.com/coopdevs/timeoverflow/blob/develop/spec/views/offers/show.html.erb_spec.rb)? Or add any test that you see necessary? Thanks!

**Comment by Morantron** [comment]
image

@enricostano ?

**Comment by sseerrggii** [comment]
I don't know why in staging I have an 500 Error on Post creation: 

FireShot Capture 198 - Banc del Temps de Gràcia - staging timeoverflow org


Looking at logs I get this lines: 

```
I, [2019-03-21T18:23:36.214866 #369]  INFO -- :   Rendered application/menus/_language_switcher.html.erb (2.3ms)
I, [2019-03-21T18:23:36.215329 #369]  INFO -- :   Rendered application/_footer.html.erb (7.6ms)
I, [2019-03-21T18:23:36.215557 #369]  INFO -- :   Rendered layouts/application.html.erb (71.9ms)
I, [2019-03-21T18:23:36.216635 #369]  INFO -- : Completed 500 Internal Server Error in 84ms (Views: 64.5ms | ActiveRecord: 10.5ms)

```
After few secons start CreatePushNotificationsJob things: 

```
I, [2019-03-21T18:24:03.274684 #376]  INFO -- : [ActiveJob] [CreatePushNotificationsJob] [260fd6fb-7f88-4568-b41c-a654e6091da6] Performing CreatePushNotificationsJob from Sidekiq(default) with arguments: {:event_id=>10334}
D, [2019-03-21T18:24:03.277478 #376] DEBUG -- : [ActiveJob] [CreatePushNotificationsJob] [260fd6fb-7f88-4568-b41c-a654e6091da6]   Event Load (0.5ms)  SELECT  "events".* FROM "events" WHERE "events"."id" = $1 LIMIT 1  [["id", 10334]]

```

**Comment by sseerrggii** [comment]
Tested
giphy

**Pull request merged**
