### PR TITLE
update to Ruby 2.6

### PR DESCRIPTION
**Pull request by markets**
:warning: This PR points to `feature/ubuntu-bionic` branch (#502)

Let's move to latest stable release :shipit:

### CODE REVIEW

**Comment by markets** [comment]
😂 not really fixing it last night, but got the Travis 🛑 email and I remembered that just recently I was fixing those problems in some gems...

IMHO yes, it's worth it! It's an "small" patch that not affects runtime, only controller tests. Since we are going to do a Ruby upgrade and test/review all app... why not? It doesn't force to upgrade Rails right now either, and anyway, we should start to think in a Rails upgrade, our current version 4.2.Z is almost out of "Severe Security Issues" (Rails 6 is in rc already).

**Comment by enricostano** [comment]
> It doesn't force to upgrade Rails right now either, and anyway, we should start to think in a Rails upgrade, our current version 4.2.Z is almost out of "Severe Security Issues" (Rails 6 is in rc already).

That's my point, we have to upgrade Rails ASAP. And that will bring latest Ruby with it.

> It's an "small" patch that not affects runtime, only controller tests. Since we are going to do a Ruby upgrade and test/review all app... why not?

OK then, let's do this! Thanks for your help as always 💪❤️

**Comment by markets** [comment]
I am a volunteer to work on the Rails upgrade :hand: 

Thanks @enricostano! :ok_hand:

**Comment by enricostano** [comment]
> I am a volunteer to work on the Rails upgrade

Cool! Perfect, let's plan the work needed 💪

**Pull request merged**
