### PR TITLE
Turbolinks 🏃

### PR DESCRIPTION
**Pull request by markets**
[Turbolinks](https://github.com/turbolinks/turbolinks#turbolinks) integration for the public part :zap: 

### Extra:
- select2 init cleanup (helps with Turbolinks integration)

### CODE REVIEW

**Comment by markets** [comment]
Hello Pau :wave: 

I'm actually using Turbolinks (v5) in 3 production apps, for more than 2 years, with 0 problems, and really happy regarding results/perfomance vs maintenance costs. For "simple" applications (like this one), where most of pages are lists and forms, and they don't have a complex UI interactivity, it works pretty good enough IMHO :ok_hand: and it's an acceptable trade-off. I take new deps for a project really seriously, but page transition seems so smooth :zap:.

Nice talk from Sam Stephenson: https://www.youtube.com/watch?v=SWEts0rlezA&t=10m49s

Let me know what do you think team. Thanks for reviewing :eyes: !

**Comment by enricostano** [comment]
@markets , many thanks! Would you mind to explain to @sseerrggii how this will impact the application from an user perspective? Which features are involved, how to test and especially which problem are we trying to address?

You know product owners.... :trollface:

**Comment by sseerrggii** [comment]
Wow! I'm excited to try this! :clap: :clap: :clap:

**Comment by sseerrggii** [comment]
Tested :green_apple: 

:heavy_check_mark: popups
:heavy_check_mark:  show-password thing in the login
:heavy_check_mark:  transfers form
:heavy_check_mark: stats pages with highcharts
:heavy_check_mark:  tags page: posts switcher
:heavy_check_mark: posts form: tags, user
:heavy_check_mark:  mobile app

**Comment by enricostano** [comment]
I'm still not 100% convinced about introducing new tech right now, sorry 🙏😥

I would look into this after Pontevedra changes. Let's create a card for it please Sergi.

**Comment by sseerrggii** [comment]
Ok @enricostano so we will discuss that after the [new features "Pontevedra"](https://community.coopdevs.org/t/reunion-mensual-timeoverflow-25-febrero-2019/845/2) 

I added to project 2019 2T https://github.com/coopdevs/timeoverflow/projects/2#card-17775160

**Comment by markets** [comment]
Closing for now, we'll revisit in the future with the new Hotwire/Turbo libraries: https://github.com/hotwired/turbo-rails

**Pull request closed without merging**
