### PR TITLE
New screenshots

### LINKED ISSUE #493: Update screenshots
Our current screenshots in docs (README) are a bit outdated, we should updated them:
- https://github.com/coopdevs/timeoverflow/blob/develop/docs/ofertas.png
- https://github.com/coopdevs/timeoverflow/blob/develop/docs/usuarios.png

### PR DESCRIPTION
**Pull request by sseerrggii**
Closes #493

### CODE REVIEW

**Comment by enricostano** [comment]
This only removes the old screenshots, right?

**Comment by markets** [comment]
Thanks a lot for working on this @sseerrggii :clap: I'd add some shadow :art: as we have in current images, they look nicer!

**Comment by sseerrggii** [comment]
Can we merge that @enricostano ?

**Comment by enricostano** [comment]
@sseerrggii did you add the shadow as in the other images or you don't think it's necessary?

**Pull request merged**
