### PR TITLE
Custom error pages

### LINKED ISSUE #265: Implement 404 page
We need to customize the Rails' default 404 page. It's not very user friendly. Looks like the server is on :fire: .

Our proposal is something functional as the following but we're open to suggestions:

photo5992211769084455444

Note that the broken left-alignment is not intended.

### PR DESCRIPTION
**Pull request by markets**
Closes #265 

Implement custom error pages: 404 and 500.

To test it locally: 
- http://127.0.0.1:3000/404
- http://127.0.0.1:3000/500

**NOTE:** `localeapp` translations integrated here :point_right: #301 

# 404
captura de pantalla 2018-01-28 a la s 22 11 42

# 500
captura de pantalla 2018-02-05 a la s 20 19 34

### CODE REVIEW

**Comment by markets** [comment]
@sseerrggii @sauloperez I made a signup on localeapp, but I think I can't create new translation keys. Could you please help me with this 😄?

We'll need 4 new segments:
- 404 title (errors.not_found.title)
- 404 description (errors.not_found.description)
- 500 title (errors.internal_server_error.title)
- 500 description (errors.internal_server_error.description)

**Comment by sauloperez** [comment]
I'm crying of joy @markets! It's wonderful to have you back! :tada:👏:muscle:

**Comment by markets** [comment]
@sauloperez i18n integration pushed => https://github.com/coopdevs/timeoverflow/pull/299/commits/11010c6be7716a55ee7a8408a1c514cc8ccc6213

**Comment by sauloperez** [comment]
Perfect @markets ! Perfect timing for this. We'll hand it over to the new testing team we're building :point_right: http://community.coopdevs.org/t/timeoverflow-testing-team/345/6

**Comment by enricostano** [comment]
@sseerrggii I deployed this branch to https://staging.timeoverflow.org for the test team to test it :muscle: 

@markets sorry I had to rebase with current `develop` and `push --force` :grimacing:

**Comment by sseerrggii** [comment]
Tested: Work Fine, thanks @markets

**Pull request merged**
