### PR TITLE
Add markdown at post description

### PR DESCRIPTION
**Pull request by sseerrggii**
Now the post description is rendered with markdown
It is my first time adding a gem so... better check well :smile:

### CODE REVIEW

**Comment by rewritten** [comment]
RDiscount is for markdown, no need for another gem. But good proposal. 

I would object just the "render engine" as a controller instance variable. 

It would be maybe better for now to fatten the Post model by adding

```
def rendered_description
  RDiscount.whatever(description)
end
```

So we are able to refactor at will (maybe passing a decorated or otherwise composed object having both the post and the renderer) and the view would not know.

**Comment by markets** [comment]
🔝  @sseerrggii 

Just a comment, could you please run `bundle install` in order to remove `redcarpet` from Gemfile.lock? 😜

**Comment by rewritten** [comment]
👍

**Comment by markets** [comment]
@sseerrggii solo una pregunta:  La variable `locale`, de donde sale en este link? "https://#{locale}.wikipedia.org/wiki/Markdown"

**Comment by sseerrggii** [comment]
@markets es el idioma, es una manera rara de hacerlo pero asi puedo mandar en función del idioma a:
 
https://es.wikipedia.org/wiki/Markdown
https://ca.wikipedia.org/wiki/Markdown
https://en.wikipedia.org/wiki/Markdown

:sweat_smile:

**Comment by markets** [comment]
Ah @sseerrggii, eso si 👍 , me refería más a que era `locale`, debe ser un "alias" de `I18n.locale` o un helper de `ActionView`? No me suena verlo por la guía de I18n, normalmente había visto llamadas a `I18n.locale`...

**Comment by sseerrggii** [comment]
@markets Pues no se, supongo que lo leí en stackoverflow :joy: :joy: Si es más claro poner `I18n.locale` lo cambio :)

**Comment by markets** [comment]
Pues la verdad que ha mi no suena `locale` a secas, pero igual es válido (i public api)... a ver que dicen @rewritten @enricostano 

Por lo demás 👍

**Comment by rewritten** [comment]
:+1:  the Wikipedia link helper is not urgent, as long as it is used just in one place. Let's see in staging if there is some problem in the bare `locale` call

**Comment by rewritten** [comment]
Rebase or merge, for me it is ready.

**Comment by sseerrggii** [comment]
Lo he puesto así `I18n.locale` y más comprensible :smile:

**Comment by enricostano** [comment]
👍

**Pull request merged**
