### PR TITLE
Add Transfers Report 

### PR DESCRIPTION
**Pull request by markets**
First part of #596 (partially extracted from #259)

**EXTRA**
- Open `Tags` section for all users. Now that we have a good ✔️  responsive page (since #547), this is very useful to explore all the content inside an organization

### CODE REVIEW

**Comment by markets** [comment]
@sseerrggii this is ready to test 😺

**Comment by sseerrggii** [comment]
Thanks @markets Good first step for #596 Also I agree to open Tags section for all users :wink: 

I tested on staging and I got this error 

Screenshot_2021-03-15 Banco de Tiempo Local


it occurred  at `https://staging.timeoverflow.org/statistics/statistics_all_transfers` and at `https://staging.timeoverflow.org/report/transfer_list` 

Info from Rollbar:

Screenshot_2021-03-15 Rollbar

**Comment by markets** [comment]
Thanks @sseerrggii, I'll take a look later, I see what's happening.

**Comment by markets** [comment]
@sseerrggii I just rebased `develop` and added a fix for that nil pointer exception

**Comment by sseerrggii** [comment]
Tested! :green_circle:

**Pull request merged**
