### PR TITLE
Update ruby 2.3.0 -> 2.5.3

### PR DESCRIPTION
**Pull request by viktorsmari**
If you first merge #443 , then this test should pass (if you force rerun it)

### CODE REVIEW

**Comment by enricostano** [comment]
@viktorsmari #443 has been merged, thanks for your time!

**Comment by viktorsmari** [comment]
Of course, Travis only builds this PR, and the other PR I made, even though it is merged to develop, does not automatically 'join' this one. 
Do you know how can we merge/rebase current develop branch into this PR?

**Comment by markets** [comment]
> does not automatically 'join' this one

ouch! yes of course :sweat_smile: I do not know why, I thought it was already rebased :pray: 

About `merge` vs `rebase`. I prefer `rebase` when I'm working alone in a branch, but `merge` when working on a shared branching project/feature. Also, now that we have an `squash` button in GitHub, I sometimes squash all commits before merging directly via the UI... So no problem, both are fine, we do not have a policy on this subject either :)

Thanks!

**Comment by viktorsmari** [comment]
I actually thought the same, that Travis would somehow know `develop` had changed!
But I pushed the rebased changes and Travis is building!

**Comment by enricostano** [comment]
Hi @viktorsmari I still see some commit from others PRs, could you please check again? Thanks!

**Comment by viktorsmari** [comment]
Hi @enricostano I just did what @markets asked me to do, to rebase this PR. 
Can you tell me the correct way to do this? :hear_no_evil:

**Comment by enricostano** [comment]
@viktorsmari did you sync your fork with latest changes upstream?

https://help.github.com/articles/syncing-a-fork/

Once you have the latest `develop` branch in your fork, go to this PR's branch and run `git rebase develop`. A forced push will be needed. I hope this will help you.

Many thanks for your time!

**Comment by viktorsmari** [comment]
Thanks for your patience @enricostano :smile: 
It was the `--force` push that was missing. 
I noticed they released a security version 2.3.8, 2 days ago, I am including it now last minute. Was that okay?

**Comment by enricostano** [comment]
Many thanks for your work on this @viktorsmari , I just want to inform you that this specific PR will be merged in a while. We're having some issues upgrading Ruby on the production machine and we're also planning to change the server in order to upgrade Ruby and more things.

So, don't worry if you see this PR not merged during some time, we still cannot say how long it will take. Sorry for the wait but keep the PRs coming! :joy: :muscle:

**Comment by viktorsmari** [comment]
What are we using in production? rvm or rbenv?
I have just been testing newer ruby versions like `2.5.3` and all rake tests pass on that! So I could make another PR for newer versions.

**Comment by enricostano** [comment]
Right now in production we're using an old server that uses a packaged version of Ruby, we don't like it and we will switch to `rbenv`. That's why in `timeoverflow-provisioning` repo the stage `production` is still missing.

As soon as we have more resources we'll be able to move forward with this plan at system administration level. I hope before the end of 2018, but it depends on many things.

**Comment by markets** [comment]
Hi @viktorsmari @enricostano, since we're going to take a while, I agree we'd upgrade to latest stable release `2.5.2` :ok_hand:

**Comment by enricostano** [comment]
This PR has been superseded by https://github.com/coopdevs/timeoverflow/pull/502

We're slooooowly moving forward updating our dependencies. I'm sorry this PR could not be merged before :disappointed:

**Pull request closed without merging**
