### PR TITLE
Responsive members page on mobile

### PR DESCRIPTION
**Pull request by mllocs**

### CODE REVIEW

**Comment by mllocs** [comment]
[Disseny vista llista d'usuaris](https://trello.com/c/ynKX3KZb/127-disseny-vista-llista-dusuaris)

**Comment by enricostano** [comment]
Changed base to `develop` since #388 has been merged.

**Comment by mllocs** [comment]
Fixed hiding the admin actions on mobile ✅

**Comment by enricostano** [comment]
Deployed on https://staging.timeoverflow.org/

**Comment by enricostano** [comment]
Tested with @sseerrggii :green_apple:

**Pull request merged**
