### PR TITLE
Fix new line styles for post description

### PR DESCRIPTION
**Pull request by sseerrggii**

### CODE REVIEW

**Comment by enricostano** [comment]
:+1:

**Comment by enricostano** [comment]
cc/ @andresgutgon

**Comment by enricostano** [comment]
cc/ @naoisegolden

**Comment by naoisegolden** [comment]
👍

**Comment by rewritten** [comment]
Interesting! Does it work on any pre-2017 browser?

**Comment by enricostano** [comment]
> Interesting! Does it work on any pre-2017 browser?

@rewritten it seems so https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#Specifications

**Comment by rewritten** [comment]
@enricostano amazing!

**Pull request merged**
