### PR TITLE
Remove LazyRecoverable and dalli (and memcached)

### LINKED ISSUE #327: Is this optimization really needed on password reset?
I still don't understand what problem we were trying to solve.

Give a look at https://github.com/coopdevs/timeoverflow/commit/f8f940050ac5677805beca4065f9cdf0f7f287bb

### LINKED ISSUE #358: Can we remove Memcached?
Since we have Redis now manage background jobs we would like to simplify our stack and just use Redis for cache also, removing Memcached.

Discussion started on https://github.com/coopdevs/timeoverflow/pull/353

### PR DESCRIPTION
**Pull request by markets**
Closes #358
Closes #327

Added `data: { disable_with: '...' }` to the button to disable it while the request is running (should avoid fast double clicks).

### CODE REVIEW

**Comment by sseerrggii** [comment]
Hi @markets we are back with new infra :tada: 
Tested :green_heart:

**Comment by sauloperez** [comment]
I created https://github.com/coopdevs/timeoverflow-provisioning/issues/144 out of this.

**Comment by markets** [comment]
cool 🤘🤘:metal:

maybe now we can revert this revert #513? would be amazing to get rid off Elastic 👌

**Comment by sauloperez** [comment]
Yep, that's the next one on the list. Probably after Xmas though.

**Comment by sauloperez** [comment]
I can confirm we are now memcached-free in production. One thing less to run :tada:

**Pull request merged**
