### PR TITLE
Release v1.10.0

### PR DESCRIPTION
**Pull request by enricostano**
Creating new release including:

* New translations for Develop branch #446
* Little improvements in /members #436 
* Definitive fix for deleting org that is current_org #432
* Travis reads the .ruby-version file #443
* adapt reset password page to new styles #419
* Render partial with collection #416
* Remove posts helper #412
* Removed offers dashboard #435

### CODE REVIEW

**Comment by enricostano** [comment]
Deployed to staging.

cc/ @sseerrggii

**Comment by sseerrggii** [comment]
Release tested :heavy_check_mark:

**Comment by sseerrggii** [comment]
Release tested :heavy_check_mark:

**Comment by sseerrggii** [comment]
Release tested :heavy_check_mark:

**Comment by sseerrggii** [comment]
Release tested :heavy_check_mark:

**Comment by sseerrggii** [comment]
Release tested :heavy_check_mark:

**Pull request merged**
