### PR TITLE
Hide admin column actions for normal users

### PR DESCRIPTION
**Pull request by sseerrggii**
Waiting for #198

### CODE REVIEW

**Comment by rewritten** [comment]
:+1:

**Comment by rewritten** [comment]
But rebase on top of new master when the linter has been fixed.

**Comment by enricostano** [comment]
Rebased :muscle: :+1:

**Comment by rewritten** [comment]
:heart: :kissing: :clap:

**Comment by rewritten** [comment]
This is worth a release.

**Comment by enricostano** [comment]
Merge?

**Comment by enricostano** [comment]
Really nice to see that our efforts on [development evironment](https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-for-GNU-Linux) are helping already! Looking forward to making it official.

:muscle: :clap:

**Comment by rewritten** [comment]
💪 ♥️

**Pull request merged**
