### PR TITLE
Rails 6.1

### PR DESCRIPTION
**Pull request by markets**
🎺 🎺  Living on the edge 🎺 🎺 

Now that we are on Rails 6, let's try to be as much updated as we can.

**NOTE** After reviewed the release changelog and played a bit locally (tests are also passing ✔️ ), this seems safe to merge

### CODE REVIEW

**Comment by markets** [comment]
Tested ✅  merging

**Comment by sseerrggii** [comment]
Ok, I will test a little bit also in staging and deploy to production :muscle:

**Comment by sauloperez** [comment]
https://twitter.com/rails/status/1347643954867687432?s=19 :trollface:

**Comment by sseerrggii** [comment]
@markets I have a problem with unicorn when I tried to deploy it to staging

When I did `sudo systemctl restart timeoverflow` seams that this unite cannot restart

2021-01-09-065248_1960x2160_scrot

When I check on log/unicorn.err.log

```
I [2021-01-09T06:43:01.612635 #4249]  INFO -- : reaped #<Process::Status: pid 4328 exit 0> worker=0
I, [2021-01-09T06:43:01.613216 #4249]  INFO -- : reaped #<Process::Status: pid 4329 exit 0> worker=1
I, [2021-01-09T06:43:01.613345 #4249]  INFO -- : master complete
I, [2021-01-09T06:43:01.613257 #4966]  INFO -- : reaped #<Process::Status: pid 5039 exit 0> worker=0
I, [2021-01-09T06:43:01.613600 #4966]  INFO -- : reaped #<Process::Status: pid 5040 exit 0> worker=1
I, [2021-01-09T06:43:01.613859 #4966]  INFO -- : master complete
I, [2021-01-09T06:43:02.203674 #5414]  INFO -- : Refreshing Gem list
bundler: failed to load command: unicorn (/var/www/timeoverflow/shared/bundle/ruby/2.6.0/bin/unicorn)
RuntimeError: Couldn't find Active Storage configuration in /var/www/timeoverflow/releases/20210109053957/config/storage.yml
```

**Pull request merged**
