### PR TITLE
add SimpleCov

### PR DESCRIPTION
**Pull request by markets**
:gem: https://github.com/colszowka/simplecov

Very useful :ok_hand: as stated by @sauloperez in #281. I think we can configure Travis with Code Climate later. 

After running the tests, you can open the generated `PROJECT_ROOT/coverage/index.html` file in a browser and you can see a detailed coverage report :sparkles: 

At this point **62.58% covered**.

### CODE REVIEW

**Comment by markets** [comment]
Current build failed on Travis, but it seems totally unrelated to this PR. 

All feature (`capybara`) specs failed, with same error: `Net::ReadTimeout:` so I'd say this is something related to the ChromeDriver installation (or the add-on in Travis)... I see other branches failing with same error, so we'll need to take a look to this point.

**Comment by enricostano** [comment]
>  I'd say this is something related to the ChromeDriver installation

@Morantron KEASECHO

**Comment by markets** [comment]
@Morantron @enricostano I started a branch to try fix this 👉 #461 

First of all, I just upgraded gems to latest versions (basically because the `chromedriver` gem https://github.com/flavorjones/chromedriver-helper#known-issues has kwown issues with our current version), but no luck :(

**Comment by markets** [comment]
@sauloperez friendly ping :smile_cat:

**Comment by sauloperez** [comment]
> At this point 62.58% covered.

Not bad

**Comment by enricostano** [comment]
@markets @sauloperez are we going to add coverage check in CI?

**Comment by sauloperez** [comment]
We should. Otherwise, coverage is not that useful.

**Comment by enricostano** [comment]
I created an issue for that https://github.com/coopdevs/timeoverflow/issues/476

**Pull request merged**
