### PR TITLE
Filter posts by organization

### PR DESCRIPTION
**Pull request by rewritten**

### CODE REVIEW

**Comment by rewritten** [comment]
@markets @carlesjove with tests :) Could anyone of you review it?

**Comment by carlesjove** [comment]
I'll check it out tonight!

**Comment by carlesjove** [comment]
Looks fine to me. I'd just point that `still_another_user` should be `yet_another_user` ;-)

**Comment by rewritten** [comment]
@carlesjove fixed.

**Comment by carlesjove** [comment]
Cool! Then I guess it's ready to go!

**Comment by markets** [comment]
LGTM :+1:

**Comment by rewritten** [comment]
@markets LGBT?

**Pull request merged**
