### PR TITLE
Update deps

### LINKED ISSUE #284: Fetch activeadmin from Rubygems instead of git
When running `bundler` commands in the repo a warning shows up:

```shell
$ ➜  timeoverflow (upgrade-to-rails4.2.7.1) bundle update rspec-rails                                                                       The git source `git://github.com/activeadmin/activeadmin.git` uses the `git` protocol, which transmits data without encryption. Disable this
 warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

We should fetch that gem from Rubygems instead of git for security reasons.

### PR DESCRIPTION
**Pull request by knoopx**
It also closes #284

### CODE REVIEW

**Comment by knoopx** [comment]
FYI: Couldn't boot the app at all until updating the deps.

**Comment by sauloperez** [comment]
really? what was the problem?

**Comment by enricostano** [comment]
@knoopx Did you start this branch from `master` or `develop`? I ask for those merge commits.

In any case, many thanks!!!

**Comment by knoopx** [comment]
@enricostano rebased from `develop`

**Comment by sauloperez** [comment]
Cool! Let's wait until Sergi tests this alongside #266 again.

**Comment by sauloperez** [comment]
Closes #284

**Comment by sauloperez** [comment]
I hope I've solved the merge conflicts in the `Gemfile.lock` correctly, might not be the wisest thing to do on a Friday afternoon :trollface:

**Pull request closed without merging**
