### PR TITLE
sort members by last_sign_in_at by default

### LINKED ISSUE #468: Sort members list by last_sign_in_at
In this commit https://github.com/coopdevs/timeoverflow/pull/436/commits/b0d675ce92a5153085411382c372fe9794cb6a73#diff-4e05ad0d64e6100656b63ad1e78f32c5R6 @mllocs  try to sort members in `/members` by last_sign_in_at but seems that ransack have troubles to sort null results at the end. 

For that we revert the change https://github.com/coopdevs/timeoverflow/pull/436/commits/9208d17bf00ef39e5d8b9d7dace87ccbc795d6df

Can we fix it? Will be good to see different members in this main page `/members`

Also is better to have members sorted by *activity* (Sorted by date of last transfer of member)

### PR DESCRIPTION
**Pull request by markets**
Closes #468 

Solution extracted and adapted from https://github.com/activerecord-hackery/ransack/issues/443. 

I tried it locally and it seems to work well (even the `manage` page with custom sorting). 

I'll fix/improve tests before merge, but maybe @sseerrggii you can take a quick look before :grin:?

TODO:
- [x] fix/improve related tests

### CODE REVIEW

**Comment by sseerrggii** [comment]
Tested in staging, works perfect! 

Thank you again @markets  :muscle: 

giphy (9)

**Comment by markets** [comment]
@sseerrggii @enricostano specs :white_check_mark: ready for review!

**Comment by markets** [comment]
Not sure why % decreased... New lines are covered ¯\_(ツ)_/¯

**Comment by enricostano** [comment]
Yeah, it complains about the `terms_controller`, that you're not touching in this PR :/

**Comment by sseerrggii** [comment]
Tested on staging :green_apple:

**Pull request merged**
