### PR TITLE
Remove TODO. This method is used in users list

### PR DESCRIPTION
**Pull request by sauloperez**
So, we can't eliminate the method and it's not that important to refactor. First, it should have specs... In any case, the problems that we have right now are not related to this method.

### CODE REVIEW

**Comment by enricostano** [comment]
@knoopx already dealt with it 💪 

https://github.com/coopdevs/timeoverflow/pull/272/files#diff-1f527483fa5f6b74202ae2c2f0c06af0

**Comment by sauloperez** [comment]
🤔  but I found that:

> This method is used in users list

if I remove it the user list is totally empty as we don't populate that data for angular to render it...

**Comment by enricostano** [comment]
You cannot remove it yet, just wait for the other PR.

**Comment by sauloperez** [comment]
Ok, got it

**Comment by enricostano** [comment]
I wouldn't even remove the TODO right now, that would create conflicts in the other PR and slower it even more 🙈

**Comment by sauloperez** [comment]
Yes, sure, no need to spend any more time on it.

**Pull request closed without merging**
