### PR TITLE
Fix several small bugs and improvements 

### LINKED ISSUE #688: Translation issue - English - change 'Truncate' in page browser to '...'
In the page browser at the bottom of the screen (when there are more members, offers, requests/inquiries than can display on one screen), it shows the page numbers and if there are a large number of pages, in between it says "truncate".
Please replace "truncate" with "..."
E.g. instead of 1, 2, 3, 4, 5, truncate, NEXT, LAST
it should be 1, 2, 3, 4, 5, ..., NEXT, LAST

### LINKED ISSUE #690: Offers listing shows &amp; instead of &
In the screen https://www.timeoverflow.org/offers, instead of showing the character "&" in an offer title or description, it displays as "&amp;". This is an HTML decoding issue.

### LINKED ISSUE #692: Inconsistent treatment of Markdown in Members display
The Member description field is inconsistent in terms of supporting Markdown formatting. Markdown formatting displays correctly when viewing an individual member's profile, but when viewing the list of members (https://www.timeoverflow.org/members), you see the formatting codes displayed.
Please change this so it works the same as offers and requests/inquiries, i.e. when viewing an individual record (member, offer, request/inquiry) it displays the formatting as expected, but when viewing the listing of members, offers and requests it should display as plain text but not showing the formatting codes.

### LINKED ISSUE #693: Newsletter still says "inquiries" in English - please change to "requests"
The weekly email newsletter still says "Lastest inquiries published:" in the English translation.
Please change this to "Lastest requests published:"

### LINKED ISSUE #696: Please change "Movements" to "Exchanges" in English translation in member profile screen
In the English translation, please change "Movements" text down the bottom of individual profiles to "Exchanges". In Spanish movimientos means transactions... but has been translated to movements which does not sound right, and the NZ timebanks would prefer "Exchanges" instead.

### PR DESCRIPTION
**Pull request by franpb14**
### Changes
- Truncate in pagination => '...' => Closes #688
- La**s**test inquiries published:=> Latest requests published: => Closes #693
- Movements => Exchanges => Closes #696
- &amp; in the posts list fixed with sanitize => Closes #690
- members description shown without markdown tags => Closes #692

### CODE REVIEW

**Review by markets — APPROVED** [review]

**Comment by markets** [comment]
@sseerrggii @franpb14 deployed to staging! We can test a bit and release to pro 🚀

**Comment by markets** [comment]
Seems to work fine 👌🏼 I'm going to merge and release

**Comment by markets** [comment]
Hello @JohnGillanders 👋🏼 

All those issues listed [here](https://github.com/coopdevs/timeoverflow/pull/698#issue-1731224838) were fixed and released to production! Thanks for reporting 👍🏼

**Comment by JohnGillanders** [comment]
Thanks so much, Marc!Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 12/06/2023, at 5:12 AM, Marc Anguera ***@***.***> wrote:﻿
Hello @JohnGillanders 👋🏼
All those issues listed here were fixed and released to production! Thanks for reporting 👍🏼

**Pull request merged**
