### PR TITLE
Add background jobs

### PR DESCRIPTION
**Pull request by enricostano**
### WAT
We need a background jobs system in order to send emails, mobile push notifications, etc.

### Dependencies
https://github.com/coopdevs/timeoverflow-provisioning/pull/47 (Install Redis)

### TODO BEFORE DEPLOY
 - [x] provision `redis` on `staging` (Ansible scripts)
 - [x] install `redis` by hand in `production` :grimacing:

### CODE REVIEW

**Comment by markets** [comment]
Nice @enricostano! Taking into account that we'll have (and we'll depend on) `redis`, we can maybe drop the `memcached` dependency and use `redis` also as a cache store, in the future, so this will simplify our infrastructure.

**Comment by sauloperez** [comment]
that's a good idea @markets . I wonder though if we can completely get rid of the cache store to simplify the infrastructure as well as the code even further.

**Comment by markets** [comment]
Yes, right now we're using caching (=> and `memcached`) only for this #327 I think :(

**Comment by sauloperez** [comment]
Yep, that's we got it in our radar. :hocho: if possible.

**Comment by enricostano** [comment]
> we can maybe drop the memcached dependency and use redis also as a cache store, in the future, so this will simplify our infrastructure.

I whish we could, I remember a conversation with sys admins about redis not being the best option for cache... but I need to dig into that again. It was probably related to performance, I'll look into it.

**Comment by sauloperez** [comment]
Could be. But keep in mind that our use case is rather small. It might be one of those cases where the tradeoff of using it as a cache store makes sense.

**Pull request merged**
