### PR TITLE
Remove posts helper

### PR DESCRIPTION
**Pull request by enricostano**
### WAT
"I love the smell of deleted code in the morning".

### Test
Test everything related to (especially links and buttons):
 - `Post`
 - `Tag`

### CODE REVIEW

**Comment by enricostano** [comment]
Deployed to staging

**Comment by sseerrggii** [comment]
I can't edit Post, but I'm not sure if is it something fixed in other PR, I remember we fixed same problem some weeks ago...


peek 17-10-2018 16-48

**Comment by enricostano** [comment]
I'll rebase it.

**Comment by sseerrggii** [comment]
Works fine :heart:!! Thanks

**Pull request merged**
