### PR TITLE
Switch to haml_lint since haml-lint does not exist anymore

### PR DESCRIPTION
**Pull request by enricostano**
### WAT
We just discovered that the gem changed its name :sob: 
https://github.com/brigade/haml-lint/issues/133

### CODE REVIEW

**Comment by markets** [comment]
hey @enricostano, or why not just ✂️  this dependency? If I'm not wrong, we don't run this Haml linter on Hound...

**Comment by enricostano** [comment]
I would love to :heart_eyes:

**Comment by enricostano** [comment]
Is that OK for you @rewritten ?

**Comment by rewritten** [comment]
Haml burn in h*ll :fire: :fire: :fire:

**Comment by rewritten** [comment]
In other words, :+1: to @markets proposal

**Comment by enricostano** [comment]
merge @rewritten ? :grimacing:

**Comment by rewritten** [comment]
:clap: :clap: :clap: Thanks @enricostano

**Pull request merged**
