### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by sseerrggii**
Translation for https://github.com/coopdevs/timeoverflow/pull/299

### CODE REVIEW

**Comment by sauloperez** [comment]
We'll need to rebase onto develop once #299 gets merged in.

**Comment by enricostano** [comment]
Rebased on top of #299 and pointed the PR against #299 

Ready to test both this and #299 on https://staging.timeoverflow.org

**Comment by sseerrggii** [comment]
Translated @markets 

fireshot capture 25 - banco de tiempo local - https___staging timeoverflow org_404

fireshot capture 26 - banco de tiempo local - https___staging timeoverflow org_500

**Comment by sauloperez** [comment]
"departamento técnico" really? :trollface:

**Pull request merged**
