### PR TITLE
Update deps - 2nd round

### LINKED ISSUE #280: Update Rubocop due to vulnerability
According to github there's a vulnerability in our version:

vulnerability

### LINKED ISSUE #297: Fix deprecation warning due to sass-rails-5.0.4
Now, with the upgrade to Rails 4.2.7.1 a new deprecation warning shows up:

```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /home/pau/dev/timeoverflow/vendor/bundle/ruby/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/railtie.rb:57)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /home/pau/dev/timeoverflow/vendor/bundle/ruby/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/railtie.rb:58)
```

It needs to be fixed before we apply another Rails upgrade.

### LINKED ISSUE #326: Remove memcachier gem
It was used for Heroku, not needed anymore. We directly use `dalli` gem to provide a `cache_store`.
[dalli](https://github.com/petergoldstein/dalli) gem is a Memcached ruby client.

### PR DESCRIPTION
**Pull request by markets**
Let's give our Gemfile and deps some more love ❤️ !! Inline with https://github.com/coopdevs/timeoverflow/pull/294. 

Supersedes and closes #273 (I cherry-picked the first commit from @knoopx to keep credit 😃 and fixed the merge with current `develop`).

## Deps changes
- Update to `Rails` 4.2.10 (latest 4.2 stable release) ~> from #273
- Update `ActiveAdmin` ~> from #273
- Update `RSpec`
- Update `nokogiri`
- Remove `quiet_assets` (now we can do the same with `sprockets-rails` 3.1+)
- Update `sass-rails` (closes #297) 
- Update `http_accept_language`
- Remove `thin`, `WEBrick` isn't that bad for dev  :raised_hands: and updated Procfile (https://github.com/coopdevs/timeoverflow/pull/298/commits/919261086f23630904d02e008a2f35ca22d60e98)
- Remove `memcachier` (closes #326 and #204)
- Update `Rubocop` to fix a security alert (https://github.com/coopdevs/timeoverflow/pull/298/commits/623fb28e31bfa152a55a218e51f9f5cef89df3d9) (closes #280). Also, removed `.hound.yml` file since we're not using it at this moment. 
- Update `Devise` to latest version (https://github.com/coopdevs/timeoverflow/pull/298/commits/75aa85d33524f2d9a55a27be9ee9e105b3ff93f1)
- Update `better_errors` (and `binding_of_caller`) (a1f68f8c7b5dccb3dc2170866a0f6e383214c0bb)
- Update `Kaminari`, necessary to make it compatible with latest (and updated also here) `ActiveAdmin` version (da98d84bcd0684501ef594c522ecab406ff4ba03)
- Update `Prawn` (https://github.com/coopdevs/timeoverflow/pull/298/commits/fda4eba10b405e2576991444045f629643f67c0b)
- Remove `foreman` (https://github.com/coopdevs/timeoverflow/pull/298/commits/8394923433ada3523df36cd116edea230c426bbd)
- Replace `high_voltage` with a custom solution (https://github.com/coopdevs/timeoverflow/pull/298/commits/2a94cf6518a2603753ab9e8a8f5d264f3f2f3480)

## Extra
- Remove unused images (https://github.com/coopdevs/timeoverflow/pull/298/commits/e4392b66ef466e2c2fcb1a500145ce86e8c1717e)
- Remove deprecated helper (https://github.com/coopdevs/timeoverflow/pull/298/commits/e4cda8b9550fad101ccb2b1c6183d3cc27ba4e72)
- Remove unused file `db/structure.sql` (74add4c8b170de1a9dc4eb290fef0335646f5e37)
- Remove deprecated file `config/deploy/shelly/after_successful_deploy` (https://github.com/coopdevs/timeoverflow/pull/298/commits/c866d333648ea7bfa40d9956591ca4767bea7299)
- Remove deprecated partial `app/views/application/_organization_list.html.erb` (https://github.com/coopdevs/timeoverflow/pull/298/commits/0e53f23fe5ae47935cd5d23eb36465f9d87b0dce)

## Note
🙏 I know this probably too big, but I think it make sense to test the whole thing together. I played (with most of touched parts) a lot locally and I found 0 errors or exceptions. Anyway, would be really nice a very good review and tests on staging.

@sauloperez you got it 👉  https://github.com/coopdevs/timeoverflow/pull/294#issuecomment-360471052 not so small finally 😛 

Also, fixes partially #289.

### CODE REVIEW

**Comment by sauloperez** [comment]
Awesome @markets ! :metal:

**Comment by sauloperez** [comment]
Great @markets ! that Rubocop vulnerability annoys me.

**Comment by sauloperez** [comment]
😍

**Comment by enricostano** [comment]
@sseerrggii deployed to https://staging.timeoverflow.org

**Comment by sseerrggii** [comment]
I did a complete test and everything seems to work well :+1:

**Pull request merged**
