### PR TITLE
profile photo for users

### LINKED ISSUE #627: Feature: profile photo for users
The idea is that the current "change your image" button will not be a link to gravatar but the user will be able to choose a photo from his computer. This photo will be stored in a backblaze bucket. 

I will not break the integration with gravatar as the default gravatar photo will continue to be used until the user changes it.

### PR DESCRIPTION
**Pull request by franpb14**
The feature #627 is finished, now the users can upload and crop their phots from their computer. I used "ActiveStorage" to store the photos and is configured to use /storage on local, to crop the photos I used "MiniMagick" and JavaScript. For the resize I used "image_processing". 

Here is the video with the feature working:

https://user-images.githubusercontent.com/70280187/117328658-225f5d00-ae94-11eb-80b6-b916bb6741df.mp4

And here is the video with the feature working on mobile (I implemented more front-end, so I saw it as appropriate):

https://user-images.githubusercontent.com/70280187/117329055-8a15a800-ae94-11eb-8577-476154879fce.mp4

**Note:** the responsive works like this in develop that's why I haven't changed it, it seems that reaching the xs size doesn't collapse as it should.

closes #627.

### CODE REVIEW

**Comment by franpb14** [comment]
@markets the problem with codeclimate coverage is that "avatar.js" is not covered?

**Comment by markets** [comment]
hello @franpb14 looks cool! I just made a quick review and I have some comments:

- the cropper panel seems a bit distorted in some axis (bottom & right), right? This looks a bit weird, can we fix it 🙏🏼 ?
- for the crop in Ruby, can we use directly the https://github.com/janko/image_processing API? Seems more readable compared to raw mini_magick IMO

**Comment by franpb14** [comment]
> * the cropper panel seems a bit distorted in some axis (bottom & right), right? This looks a bit weird, can we fix it 🙏🏼 ?

Yes, I was looking for a way to mark that dragging from those edges made the resize, but it looks a bit weird. Do I just put them normal or do I look for a way to mark it? @markets

**Comment by markets** [comment]
How it will look "normal"?

**Comment by franpb14** [comment]
As top and left

**Comment by markets** [comment]
Ah! got it, then I'd say yes 😃

**Comment by markets** [comment]
@franpb14 I pushed some clean up here: https://github.com/coopdevs/timeoverflow/pull/635/commits/608680ffef0863872230f6e812a89a9b811e5f44

Pending stuff before testing:
- Prepare ENV vars for AWS in infra: https://github.com/coopdevs/timeoverflow-provisioning

@sseerrggii maybe Pau can help us with that?

**Comment by sseerrggii** [comment]
@sauloperez could you help with that? 

Prepare ENV vars for AWS in infra: https://github.com/coopdevs/timeoverflow-provisioning (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_BUCKET, AWS_REGION) for staging and production

**Review by markets — APPROVED** [review]

**Comment by sseerrggii** [comment]
it will work on staging? or I should wait @markets ?

**Comment by markets** [comment]
We should wait @sseerrggii, we'll need to create the bucket and provision the ENV vars first.

**Comment by sauloperez** [comment]
@sseerrggii and I thought this could be a good fit for @konykon with the help of @danypr92

**Comment by konykon** [comment]
@sseerrggii @markets ENV vars for AWS added.

**Comment by markets** [comment]
Nice! thanks @konykon 👍🏼  

@sseerrggii if staging server is provisioned, we can deploy this branch to staging.

**Comment by sseerrggii** [comment]
When I tested on staging I got an error, details from Rollbar:

```
MiniMagick::Error: You must have ImageMagick or GraphicsMagick installed (Most recent call first)
Show 15 non-project frames
File /var/www/timeoverflow/releases/20210602101248/app/controllers/users_controller.rb line 145 in crop_image_and_save
File /var/www/timeoverflow/releases/20210602101248/app/controllers/users_controller.rb line 74 in update_avatar
Show 245 non-project frames
```

Maybe we need to install ImageMagick on staging and production too? @markets

**Comment by markets** [comment]
Ah right! we'll also need `ImageMagick` in our servers.

**Comment by sauloperez** [comment]
`#classic` :joy:

**Comment by sauloperez** [comment]
sounds like something you could also do if you have some room @konykon .

**Comment by konykon** [comment]
> When I tested on staging I got an error, details from Rollbar:
> 
> ```
> MiniMagick::Error: You must have ImageMagick or GraphicsMagick installed (Most recent call first)
> Show 15 non-project frames
> File /var/www/timeoverflow/releases/20210602101248/app/controllers/users_controller.rb line 145 in crop_image_and_save
> File /var/www/timeoverflow/releases/20210602101248/app/controllers/users_controller.rb line 74 in update_avatar
> Show 245 non-project frames
> ```
> 
> Maybe we need to install ImageMagick on staging and production too? @markets

Installed, can you try again?

**Comment by sseerrggii** [comment]
Yes! Seams that ImageMagick is installed now. 

Now I get this error

`Aws::S3::Errors::NoSuchBucket: The specified bucket does not exist (Most recent call first)`

In AWS what I see this

Screenshot 2021-06-07 at 09-15-48 S3 Management Console

**Comment by markets** [comment]
@sseerrggii @konykon now that I see this screenshot, I'd like to suggest to create 2 different buckets:
- timeoverflow_staging
- timeoverflow_production

**Comment by sseerrggii** [comment]
@markets I created to buckets but with "-" insted of "_" because it's a not allowed character

- timeoverflow-staging
- timeoverflow-production

What is the next step?

**Comment by markets** [comment]
ok! thanks @sseerrggii! Now, ideally the `timeoverflow-provisioning` repo should reflect this change, and provide those ENV vars taking into account we have separated buckets for each environment (IMO the bucket names don't need to be encrypted).

**Comment by konykon** [comment]
@markets I adapted the bucket and region variables but the same error appears. 
```Aws::S3::Errors::NoSuchBucket: The specified bucket does not exist```
I see AWS suggests to use an IAM User or Role to access S3 Storage Lens dashboards, in order to do that you must grant the requisite IAM permissions to a new or existing IAM user. 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage_lens_iam_permissions.html
After the last intent another error appeared as well, it seems to be related with the Ruby app.
```ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError```

**Comment by markets** [comment]
maybe we just need to re-deploy (or re-start) the app? Because the Rails master process doesn't know about those new ENV vars values added (read here, at boot time: https://github.com/coopdevs/timeoverflow/pull/635/files#diff-188abe2a4493506d81577fbbee0b279b889e59f50d509402fbbfb620c8e58780R9-R14)

**Comment by sseerrggii** [comment]
That's it @markets restarting the app works fine! :tada:

**Comment by sseerrggii** [comment]
One more thing, in production the image is saved on S3 but it's not showing properly

Rollbar says

```Aws::S3::Errors::BadRequest: Aws::S3::Errors::BadRequest```

I checked the buckets and both staging & production have the same configuration, what do you think @konykon @markets ?

**Comment by markets** [comment]
👋🏼  @sseerrggii @konykon I just checked in production, and I got this error message:

Captura de pantalla 2021-06-15 a las 0 39 59

So, it seems a miss-configuration of the bucket region: 

> Error parsing the X-Amz-Credential parameter; the region 'us-east-1' is wrong; expecting 'eu-west-3'

**Comment by sseerrggii** [comment]
Yes, we re-provision production and now works fine!! 

Thanks @markets @konykon and @franpb14 

It was a long journey, but we made it! :boom:

**Comment by markets** [comment]
Thank you so much to everybody involved in this project! 👏🏼  ⌛ 🚀

**Pull request merged**
